apiVersion: apps/v1
kind: Deployment
metadata: 
    name: kuber-dp
    labels:
        app: kuber-dp
spec:
    replicas: 1
    selector:
        matchLabels:
            env: dev
    template:
        metadata:
            labels:
                env: dev
        spec:
            containers:
            -   name: app-kuber-container
                image: stepchig/testproject:latest
                imagePullPolicy: "Always"
                ports:
                   - containerPort: 8000
                env:
                - name: databaseName
                  valueFrom:
                    configMapKeyRef:
                      name: my-mongodb-config
                      key: databaseName
                - name: collectionName
                  valueFrom:
                    configMapKeyRef:
                      name: my-mongodb-config
                      key: collectionName
                