replicaCount: 1

image:
  repository: "mongo"
  tag: "4.4"
  pullPolicy: IfNotPresent

nameOverride: "my-mongodb"
fullnameOverride: "my-mongodb-mongo-svc"

service:
  name: "my-mongodb-mongo-svc"
  type: "ClusterIP"
  port: 27017

resources: {}

# MongoDB credentials
mongodb:
  rootPassword: "adminpassword"
  username: "admin"
  password: "adminpassword"
  
container:
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"