apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-helm-chart.fullname" . }}
  labels:
    app: {{ include "mongodb-helm-chart.name" . }}
spec:
  selector:
    app: {{ include "mongodb-helm-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 27017
  type: {{ .Values.service.type }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"