apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-helm-chart.fullname" . }}
  labels:
    app: {{ include "mongodb-helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongodb-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb-helm-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources: {{ .Values.container.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-helm-chart.fullname" . }}
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-helm-chart.fullname" . }}
                  key: password
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-helm-chart.fullname" . }}
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-helm-chart.fullname" . }}
                  key: password