apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-helm-chart.fullname" . }}
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc | quote }}
  password: {{ .Values.mongodb.password | b64enc | quote }}